name: PaperTok
options:
  bundleIdPrefix: com.papertok
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

settings:
  base:
    PRODUCT_NAME: PaperTok
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

targets:
  PaperTok:
    type: application
    platform: iOS
    sources:
      - path: .
        includes:
          - "*.swift"
          - "Models/**/*.swift"
          - "Views/**/*.swift"
          - "Services/**/*.swift"
          - "Persistence/**/*.swift"
          - "Security/**/*.swift"
        excludes:
          - "Package.swift"
          - "README.md"
      - path: Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: PaperTok
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.papertok.app
        INFOPLIST_FILE: Info.plist
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
